Linear regression is a statistical method determining the relationship between two or more variables. 
It involves using an independent or known variable to predict the dependent or response variable. 
Simple: This type involves estimating the relationship between two quantitative variables, 
        such as the value of a dependent variable at a particular value of the independent variable.
Multiple: In this type, you can determine the relationship between several independent variables 
         and a dependent variable.
In this Analysis taken dataset is about the scores of a race that are mathscore,readingscore,writingscore.


In [70]:
#libraries are imported
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [71]:
#Dataset is imported and displayed
dataset= pd.read_csv(r'C:\Users\DELL\Downloads\exams.csv')
display(dataset)

race  mathscore  readingscore  writingscore
0   group B         71            79            81
1   group B         39            48            47
2   group A         61            67            64
3   group A         68            79            82
4   group B         66            86            77
..      ...        ...           ...           ...
95  group C         79            85            86
96  group D         63            73            76
97  group C         47            61            61
98  group C         76            90            87
99  group C         82            88            92

[100 rows x 4 columns]

In [72]:
#Race column is removed because the predicted value it gives when doing the onehotencoding is
#not accurate
dataset1 = dataset.drop(["race"],axis=1)
print("\nDataFrame with column removed:")
display(dataset1)


DataFrame with column removed:


mathscore  readingscore  writingscore
0          71            79            81
1          39            48            47
2          61            67            64
3          68            79            82
4          66            86            77
..        ...           ...           ...
95         79            85            86
96         63            73            76
97         47            61            61
98         76            90            87
99         82            88            92

[100 rows x 3 columns]

In [73]:
#extracted the dependent and independent variables from the given dataset. 
X = dataset1.iloc[:, :-1].values
y = dataset1.iloc[:, 2].values
print(X)
print(y)

[[ 71  79]
 [ 39  48]
 [ 61  67]
 [ 68  79]
 [ 66  86]
 [ 57  49]
 [ 81  73]
 [ 53  54]
 [ 54  51]
 [ 81  69]
 [ 59  54]
 [ 72  58]
 [ 74  64]
 [ 47  54]
 [ 67  64]
 [ 62  67]
 [ 94  95]
 [ 79  69]
 [ 31  39]
 [ 65  63]
 [ 77  86]
 [ 33  28]
 [ 80  80]
 [ 43  37]
 [ 53  74]
 [ 76  76]
 [ 69  77]
 [100  95]
 [ 64  68]
 [ 56  59]
 [ 69  74]
 [ 89  87]
 [ 89  92]
 [ 85  87]
 [ 92  93]
 [ 83  89]
 [ 85  78]
 [ 72  87]
 [ 61  66]
 [ 69  60]
 [ 68  69]
 [ 77  72]
 [ 70  66]
 [ 57  76]
 [ 98  94]
 [ 71  77]
 [ 78  84]
 [ 51  73]
 [ 93 100]
 [ 57  71]
 [ 53  64]
 [ 76  80]
 [ 67  64]
 [ 88  80]
 [ 84  80]
 [ 57  52]
 [ 68  76]
 [ 55  49]
 [ 76  90]
 [ 74  71]
 [ 69  75]
 [ 86  84]
 [ 78  93]
 [ 79  76]
 [ 67  71]
 [ 58  49]
 [ 45  55]
 [ 64  74]
 [ 43  58]
 [ 67  61]
 [ 57  57]
 [ 88  97]
 [ 57  64]
 [ 65  59]
 [ 69  73]
 [ 58  77]
 [ 56  59]
 [ 84  87]
 [ 85  78]
 [ 30  40]
 [ 90  90]
 [ 65  68]
 [ 85  93]
 [100 100]
 [ 83  76]
 [ 36  41]
 [ 84  79]
 [ 85  84]
 [ 66  70]
 [ 71  73]
 [ 78  73]

we will split both variables into the test set and training set.
We have 30 observations, so we will take 80 observations for the training set and 20 observations for the test set. We are splitting our dataset so that we can train our model using a training dataset and then test the model using a test dataset.
Here dataset has multiple columns so for this Multiple linear regression is choosen.

In [74]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =10)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 78  73]
 [ 57  57]
 [ 53  64]
 [ 98  94]
 [ 56  59]
 [ 57  52]
 [ 33  28]
 [ 86  84]
 [ 81  73]
 [ 79  76]
 [ 70  66]
 [ 92  93]
 [ 83  76]
 [ 67  64]
 [ 83  89]
 [ 69  60]
 [ 71  77]
 [ 66  86]
 [ 57  49]
 [ 93 100]
 [ 89  92]
 [ 77  86]
 [100 100]
 [ 76  90]
 [ 51  73]
 [ 90  90]
 [ 79  69]
 [ 64  74]
 [ 65  68]
 [ 53  54]
 [ 85  84]
 [ 47  61]
 [ 76  90]
 [ 82  88]
 [ 53  74]
 [ 59  54]
 [ 63  73]
 [ 84  79]
 [ 68  76]
 [ 88  97]
 [ 43  37]
 [ 80  80]
 [ 59  57]
 [ 70  80]
 [ 31  39]
 [100  95]
 [ 66  70]
 [ 55  49]
 [ 89  87]
 [ 58  49]
 [ 74  64]
 [ 85  93]
 [ 69  74]
 [ 58  77]
 [ 76  76]
 [ 47  54]
 [ 67  61]
 [ 84  87]
 [ 36  41]
 [ 76  80]
 [ 57  71]
 [ 85  78]
 [ 57  64]
 [ 85  87]
 [ 78  93]
 [ 84  80]
 [ 72  58]
 [ 94  95]
 [ 85  78]
 [ 68  69]
 [ 71  79]
 [ 65  59]
 [ 54  51]
 [ 56  59]
 [ 80  92]
 [ 71  73]
 [ 64  68]
 [ 67  71]
 [ 62  67]
 [ 81  69]]
[ 72  57  62  89  60  55  25  86  71  81  54  98  81  52  94  63  72  77
  45 100  86  90 100  84  73  89  71  67  56  

In [75]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

The last step of model is checking the performance of the model.
It can be done by predicting the test set result. For prediction, create a y_pred and x_pred vector.

In [76]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
print(y_pred)
X_pred= regressor.predict(X_train)  
print(X_pred)

[61.60945701 62.68811538 73.29750848 84.68211668 52.70554213 76.87679349
 37.55559629 70.90541045 64.15881231 55.39222139 65.10014672 45.70422939
 73.18011783 79.19136751 83.28008173 71.29744902 68.08140723 75.06278665
 69.7580901  82.27008534]
[71.91540684 55.41215471 61.72684765 93.05666903 57.22616155 50.70548267
 26.46556933 82.81938118 72.12139278 74.80807205 64.77677014 91.70336274
 75.08271997 62.68811538 87.32006728 59.0601017  75.20011061 83.32881039
 47.88147944 98.36136558 90.55604239 84.08409217 98.84199945 87.78076783
 70.06153337 88.74203556 68.21873119 71.89547352 66.31612905 52.31350356
 82.7507192  58.49087254 87.78076783 86.31007089 71.14019174 52.72547545
 70.88547713 77.97538518 74.05279026 95.19405246 35.62419881 78.64207166
 55.54947867 77.95545186 36.68292386 94.1353274  68.26745985 47.74415548
 85.84937035 47.95014142 63.16874924 91.22272888 72.23878343 74.30750487
 74.60208611 51.90153168 59.86411215 85.50606045 38.90890258 78.36742374
 68.59083643 77.10271275 

In [77]:
print('Train Score: ', regressor.score(X_train, y_train))  
print('Test Score: ', regressor.score(X_test, y_test))  

Train Score:  0.9115316662858928
Test Score:  0.9076822589881861


Evaluation Metrics
Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and R-squared

In [78]:
# Model score - R2 or coeff of determinant
# R^2=1–RSS / TSS
regressor.score(X_test, y_test)

0.9076822589881861

In [79]:
# Let us check the sum of squared errors by predicting value of y for training cases and 
# subtracting from the actual y for the training cases

mse = np.mean((regressor.predict(X_test) - y_test)**2)
print(mse)

15.345747294041285


In [80]:
import math

math.sqrt(mse)

3.9173648405581636

In [81]:
dataset1['total'] = dataset1['mathscore'] + dataset1['readingscore']
print("\nDataFrame with new column:")
display(dataset1)


DataFrame with new column:


mathscore  readingscore  writingscore  total
0          71            79            81    150
1          39            48            47     87
2          61            67            64    128
3          68            79            82    147
4          66            86            77    152
..        ...           ...           ...    ...
95         79            85            86    164
96         63            73            76    136
97         47            61            61    108
98         76            90            87    166
99         82            88            92    170

[100 rows x 4 columns]

In [82]:
X = dataset1.iloc[:, :-2].values
y = dataset1.iloc[:, 3].values
print(X)
print(y)

[[ 71  79]
 [ 39  48]
 [ 61  67]
 [ 68  79]
 [ 66  86]
 [ 57  49]
 [ 81  73]
 [ 53  54]
 [ 54  51]
 [ 81  69]
 [ 59  54]
 [ 72  58]
 [ 74  64]
 [ 47  54]
 [ 67  64]
 [ 62  67]
 [ 94  95]
 [ 79  69]
 [ 31  39]
 [ 65  63]
 [ 77  86]
 [ 33  28]
 [ 80  80]
 [ 43  37]
 [ 53  74]
 [ 76  76]
 [ 69  77]
 [100  95]
 [ 64  68]
 [ 56  59]
 [ 69  74]
 [ 89  87]
 [ 89  92]
 [ 85  87]
 [ 92  93]
 [ 83  89]
 [ 85  78]
 [ 72  87]
 [ 61  66]
 [ 69  60]
 [ 68  69]
 [ 77  72]
 [ 70  66]
 [ 57  76]
 [ 98  94]
 [ 71  77]
 [ 78  84]
 [ 51  73]
 [ 93 100]
 [ 57  71]
 [ 53  64]
 [ 76  80]
 [ 67  64]
 [ 88  80]
 [ 84  80]
 [ 57  52]
 [ 68  76]
 [ 55  49]
 [ 76  90]
 [ 74  71]
 [ 69  75]
 [ 86  84]
 [ 78  93]
 [ 79  76]
 [ 67  71]
 [ 58  49]
 [ 45  55]
 [ 64  74]
 [ 43  58]
 [ 67  61]
 [ 57  57]
 [ 88  97]
 [ 57  64]
 [ 65  59]
 [ 69  73]
 [ 58  77]
 [ 56  59]
 [ 84  87]
 [ 85  78]
 [ 30  40]
 [ 90  90]
 [ 65  68]
 [ 85  93]
 [100 100]
 [ 83  76]
 [ 36  41]
 [ 84  79]
 [ 85  84]
 [ 66  70]
 [ 71  73]
 [ 78  73]

In [83]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 69  75]
 [ 90  90]
 [ 78  73]
 [ 43  58]
 [ 76  80]
 [100  95]
 [ 31  39]
 [ 68  76]
 [ 79  76]
 [ 69  73]
 [ 39  48]
 [ 86  84]
 [ 70  66]
 [ 77  72]
 [ 66  86]
 [ 62  67]
 [ 79  69]
 [ 68  69]
 [ 61  66]
 [ 57  49]
 [ 59  57]
 [ 74  71]
 [ 71  79]
 [ 92  93]
 [ 64  68]
 [ 53  64]
 [ 72  58]
 [ 83  89]
 [ 43  37]
 [ 67  64]
 [ 59  54]
 [ 89  87]
 [ 45  55]
 [ 55  49]
 [ 30  40]
 [ 36  41]
 [ 89  92]
 [ 83  76]
 [ 67  64]
 [ 71  73]
 [ 65  63]
 [ 56  59]
 [ 57  71]
 [ 47  61]
 [ 76  90]
 [ 67  61]
 [ 77  86]
 [ 70  80]
 [ 57  64]
 [ 84  87]
 [ 76  76]
 [ 72  87]
 [ 65  68]
 [ 78  84]
 [ 69  60]
 [ 58  49]
 [ 76  90]
 [ 74  64]
 [ 66  70]
 [ 57  57]
 [ 85  84]
 [ 85  78]
 [ 33  28]
 [100 100]
 [ 81  69]
 [ 63  73]
 [ 64  74]
 [ 67  71]
 [ 51  73]
 [ 98  94]]
[144 180 151 101 156 195  70 144 155 142  87 170 136 149 152 129 148 137
 127 106 116 145 150 185 132 117 130 172  80 131 113 176 100 104  70  77
 181 159 131 144 128 115 128 108 166 128 163 150 121 171 152 159 133 162
 129 107 1

In [84]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [85]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
print(y_pred)
X_pred= regressor.predict(X_train)  
print(X_pred)

[146. 163. 128. 109. 135. 172. 189. 124. 164. 164. 168. 146. 163. 101.
 107. 143. 160. 127. 172. 105. 133. 171. 147. 185. 148. 193. 154. 170.
 178. 115.]
[144. 180. 151. 101. 156. 195.  70. 144. 155. 142.  87. 170. 136. 149.
 152. 129. 148. 137. 127. 106. 116. 145. 150. 185. 132. 117. 130. 172.
  80. 131. 113. 176. 100. 104.  70.  77. 181. 159. 131. 144. 128. 115.
 128. 108. 166. 128. 163. 150. 121. 171. 152. 159. 133. 162. 129. 107.
 166. 138. 136. 114. 169. 163.  61. 200. 150. 136. 138. 138. 124. 192.]


In [86]:
print('Train Score: ', regressor.score(X_train, y_train))  
print('Test Score: ', regressor.score(X_test, y_test))  

Train Score:  1.0
Test Score:  1.0


Applications of linear regression:
Market analysis:You can use a regression model to determine how products perform in the market by
                establishing the relationships between several quantitative variables, such as social
                media engagement, pricing and number of sales. This information allows you to utilise
                specific marketing strategies to maximise sales and increase revenue.
Financial analysis:Financial analysts use linear models to evaluate a company's
                   operational performance and forecast returns on investment.
Medicine:Medical researchers can use this regression model to determine the relationship between
         independent characteristics, such as age and body weight, and dependent ones, such as blood
         pressure. This can help reveal the risk factors associated with diseases. They can use this
         information to identify high-risk patients and promote healthy lifestyles.
Predicting outcomes,Sports analysis,Environmental health etc.
LIMITATIONS OF Linear regression:
Linearity: The assumption of linearity between variables restricts linear regressions.The premise of
           a straight-line relationship is usually false and may provide inaccurate results.
Overfit: It's not recommended to use linear regressions when the observations aren't 
         proportional to the features. Using it may produce extreme similarities between an 
         analysis and a data set and may end up failing to produce reliable results and predict
         future observations accurately.
Outliers: Linear regressions are prone to mistakes and outliers. They multiply the need for 
          analysts to analyze and remove any anomaly before applying linear regression to the data.
Multicollinearity: It's often crucial to remove any trace of multicollinearity because of its 
                   assumption that no relationship exists among the independent variables.
                   You can remove them through dimensionality reduction methods.